set_property PACKAGE_PIN Y18 [get_ports clk]
set_property PACKAGE_PIN R1 [get_ports button1]
set_property PACKAGE_PIN P1 [get_ports button2]
set_property PACKAGE_PIN P5 [get_ports button3]
set_property PACKAGE_PIN C19 [get_ports en[0]]
set_property PACKAGE_PIN E19 [get_ports en[1]]
set_property PACKAGE_PIN D19 [get_ports en[2]]
set_property PACKAGE_PIN F18 [get_ports en[3]]
set_property PACKAGE_PIN E18 [get_ports en[4]]
set_property PACKAGE_PIN B20 [get_ports en[5]]
set_property PACKAGE_PIN A20 [get_ports en[6]]
set_property PACKAGE_PIN A18 [get_ports en[7]]
set_property PACKAGE_PIN F15 [get_ports cx[7]]
set_property PACKAGE_PIN F13 [get_ports cx[6]]
set_property PACKAGE_PIN F14 [get_ports cx[5]]
set_property PACKAGE_PIN F16 [get_ports cx[4]]
set_property PACKAGE_PIN E17 [get_ports cx[3]]
set_property PACKAGE_PIN C14 [get_ports cx[2]]
set_property PACKAGE_PIN C15 [get_ports cx[1]]
set_property PACKAGE_PIN E13 [get_ports cx[0]]


set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports button1]
set_property IOSTANDARD LVCMOS33 [get_ports button2]
set_property IOSTANDARD LVCMOS33 [get_ports button3]
set_property IOSTANDARD LVCMOS33 [get_ports en[0]]
set_property IOSTANDARD LVCMOS33 [get_ports en[1]]
set_property IOSTANDARD LVCMOS33 [get_ports en[2]]
set_property IOSTANDARD LVCMOS33 [get_ports en[3]]
set_property IOSTANDARD LVCMOS33 [get_ports en[4]]
set_property IOSTANDARD LVCMOS33 [get_ports en[5]]
set_property IOSTANDARD LVCMOS33 [get_ports en[6]]
set_property IOSTANDARD LVCMOS33 [get_ports en[7]]
set_property IOSTANDARD LVCMOS33 [get_ports cx[0]]
set_property IOSTANDARD LVCMOS33 [get_ports cx[1]]
set_property IOSTANDARD LVCMOS33 [get_ports cx[2]]
set_property IOSTANDARD LVCMOS33 [get_ports cx[3]]
set_property IOSTANDARD LVCMOS33 [get_ports cx[4]]
set_property IOSTANDARD LVCMOS33 [get_ports cx[5]]
set_property IOSTANDARD LVCMOS33 [get_ports cx[6]]
set_property IOSTANDARD LVCMOS33 [get_ports cx[7]]




